"""
main.py — FastAPI application entry point.

CONCEPT: FastAPI application lifecycle
----------------------------------------
A FastAPI app goes through a lifecycle:
  1. Startup  — connect to DB, Redis, load config
  2. Running  — handle requests (this is 99% of the time)
  3. Shutdown — close connections cleanly

We manage this via the `lifespan` context manager (introduced in FastAPI 0.93).
It replaced the older @app.on_event("startup") decorators.

CONCEPT: Middleware
--------------------
Middleware wraps every request before it hits your route handlers.
CORSMiddleware handles Cross-Origin Resource Sharing — browsers block
requests from one domain (localhost:3000) to another (localhost:8000)
unless the server explicitly allows it. We configure allowed origins
in settings.ALLOWED_ORIGINS.

CONCEPT: API versioning (/api/v1)
-----------------------------------
We prefix all routes with /api/v1. When we make breaking changes in the
future (new response shapes, removed fields), we create /api/v2 and keep
v1 alive for existing clients. This is standard REST API practice.

HOW TO RUN:
  uvicorn app.main:app --reload
  - app.main   → the file (backend/app/main.py)
  - app        → the FastAPI() instance inside that file
  - --reload   → auto-restart on file changes (development only)

API DOCS (auto-generated by FastAPI):
  http://localhost:8000/docs      ← Swagger UI (interactive)
  http://localhost:8000/redoc     ← ReDoc (cleaner read)
  http://localhost:8000/openapi.json ← raw OpenAPI schema
"""

import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.core.config import settings
from app.core.database import init_db
from app.core.logging import configure_logging
from app.core.redis import close_redis
from app.api.v1.router import api_router
from app.services import analytics

# Before anything else can log — every app.* logger becomes JSON from here on.
configure_logging()
logger = logging.getLogger(__name__)

# Error tracking — opt-in by env var, same no-op-when-unset pattern as
# PostHog (services/analytics.py). Must happen before anything else that
# could raise, so Sentry is watching from the earliest possible point.
if settings.SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=settings.SENTRY_DSN,
        environment=settings.APP_ENV,
        # Full error capture; a sample of transactions for performance data —
        # 100% here would double Sentry's event volume for little benefit
        # at this traffic level.
        traces_sample_rate=0.1,
    )

IS_PROD = settings.APP_ENV == "production"
_DEFAULT_SECRET = "change-me-in-production"

if IS_PROD and settings.SECRET_KEY == _DEFAULT_SECRET:
    raise RuntimeError(
        "SECRET_KEY is still the default in production. Set a strong random "
        "SECRET_KEY — it keys the encryption for Swiggy tokens at rest."
    )


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Manage application startup and shutdown.

    Everything before `yield` runs on startup.
    Everything after `yield` runs on shutdown.

    This is an async context manager — the `async with` in FastAPI's
    internals calls __aenter__ (startup) and __aexit__ (shutdown) for us.
    """
    # STARTUP
    await init_db()  # Create DB tables if they don't exist
    yield
    # SHUTDOWN
    analytics.shutdown()  # flush queued PostHog events (no-op if disabled)
    await close_redis()  # Close Redis connection pool cleanly


app = FastAPI(
    title="Soiree API",
    description="Life events concierge powered by Swiggy MCP — Food, Instamart, Dineout",
    version="1.4.0",
    lifespan=lifespan,
    # Interactive docs + raw schema are dev-only.
    docs_url=None if IS_PROD else "/docs",
    redoc_url=None if IS_PROD else "/redoc",
    openapi_url=None if IS_PROD else "/openapi.json",
)

async def _catch_unhandled_exceptions(request: Request, call_next):
    """
    CONCEPT: why this has to be middleware, not @app.exception_handler
    -----------------------------------------------------------------------
    The obvious approach — @app.exception_handler(Exception) — doesn't
    work for this. Starlette special-cases a handler registered for the
    bare Exception class (or status 500): it pulls it out and hands it to
    ServerErrorMiddleware, which Starlette places OUTSIDE every
    app.add_middleware() middleware, CORS included (see
    Starlette.build_middleware_stack — user middleware sits between
    ServerErrorMiddleware and ExceptionMiddleware). A response built by
    that handler never passes back through CORSMiddleware, so it never
    gets an Access-Control-Allow-Origin header — the browser then reports
    a "blocked by CORS policy" error that has nothing to do with CORS,
    masking whatever the real 500 was. Verified empirically: a working
    endpoint got the header, an endpoint caught by @app.exception_handler
    didn't, from the exact same origin.

    A plain try/except *inside* middleware doesn't have this problem —
    it's just a function running in the normal request path. As long as
    it's registered BEFORE CORSMiddleware (Starlette's add_middleware
    prepends, so the middleware added LAST ends up OUTERMOST — see the
    ordering below), CORS wraps this middleware, and this middleware's
    JSONResponse goes out through the same `send` CORS already wrapped.
    """
    try:
        return await call_next(request)
    except Exception as exc:  # noqa: BLE001 — this is the last-resort catch-all
        logger.error(
            "Unhandled exception",
            exc_info=exc,
            extra={"path": request.url.path, "method": request.method},
        )
        if settings.SENTRY_DSN:
            import sentry_sdk

            sentry_sdk.capture_exception(exc)
        return JSONResponse(
            status_code=500,
            content={"detail": "Something went wrong on our end. Please try again."},
        )


# Registered BEFORE CORSMiddleware so CORS ends up outermost, wrapping this
# — see _catch_unhandled_exceptions' docstring for why the order matters.
app.add_middleware(BaseHTTPMiddleware, dispatch=_catch_unhandled_exceptions)

# CORS — allow the Next.js frontend to call this API from the browser.
# In development: localhost:3000
# In production: your actual domain (set in .env → ALLOWED_ORIGINS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,  # needed for cookies/auth headers
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount all API routes under /api/v1
# The router itself is defined in api/v1/router.py
app.include_router(api_router, prefix="/api/v1")


@app.get("/health", tags=["system"])
async def health():
    """
    Health check endpoint. Used by:
    - Docker/Railway to verify the container is alive
    - Load balancers to route traffic only to healthy instances
    - Your own sanity when something breaks
    """
    return {"status": "ok", "service": "soiree-api", "version": "1.4.0"}
